# Generated by Django 4.0.6 on 2022-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='maps',
            field=models.URLField(blank=True, null=True),
        ),
    ]
